### ISSUE TITLE
[Need Maintainer/Owner]

### ISSUE THREAD

**Issue by rosskevin** [drscream/bamboozled-ruby-plugin#25]
We have switched our focus to using [docker-rails](https://github.com/alienfast/docker-rails#ci-setup) (in bamboo and other ci servers) so we are actually not using this plugin anymore.

If you are interested in maintaining, please let me know and I'll consider adding you as a collaborator.

If you are interested in taking ownership, please let me know and I'll checkout your profile.  I have transferred repos before that were immediately abandoned; I'd like to see this continue.

**Comment by drscream** [comment]
Hello,

feel free to check my profile, I will do my best to take the ownership of the repository and project.

Best regards,
Thomas

**Comment by rosskevin** [comment]
Sounds good @drscream.  I'd like to takedown the atlassian marketplace version, so here's the steps I propose:

1. transfer repo
2. you get published on atlassian marketplace
3. notify me and I'll takedown our atlassian marketplace listing

Sound good? Do you have an alternate plan?

**Comment by drscream** [comment]
Sound like a Plan, lets do it! I will be at fosdem this weekend, so I will publish the version on Monday or Tuesday

**Comment by rosskevin** [comment]
@drscream please delete the repo from your profile.  I have merged your PR so you are safe to do so:

`drscream/bamboozled-ruby-plugin already exists`

**Comment by drscream** [comment]
I've renamed the current repository on my end

**Comment by rosskevin** [comment]
You'll have to delete it.

`drscream already has a repository in the rosskevin/bamboozled-ruby-plugin network`

**Comment by drscream** [comment]
Sorry my bad, it's deleted!

**Comment by drscream** [comment]
Thank you @rosskevin for moving the repository, I'm happy to maintain the project. Is it okey for you if I remove the webhook or is currently required in your infrastructure?

**Comment by rosskevin** [comment]
It's all yours, I don't need the we hook.

**Comment by drscream** [comment]
Hello @rosskevin,

would you please so kind and remove the plugin form the Atlassian Marktplace? I would publish it on the same unique name so less issues for the users.

Best regards,
Thomas

**Comment by rosskevin** [comment]
It appears that I cannot remove it.  I will change the vendor and add you as an admin.  Which email would you like to use?

**Comment by drscream** [comment]
Please use `tm+atlassian@core.io` for the admin account at the marketplace. Thanks a lot!

**Comment by rosskevin** [comment]
You are set, go ahead and alter the vendor information.  I downloaded a simple commons licensed vendor logo to replace the company one.

Thanks for taking over!
