### ISSUE TITLE
Timeline for Bamboo v6.2.2 support?

### ISSUE THREAD

**Issue by shaunakv1-noaa** [drscream/bamboozled-ruby-plugin#30]
Hello, we just upgraded to Bamboo v6.2.2 from v5.14.1 and all our builds are breaking as this plugin is not available on v6.2.2 yet. Is support for v6.2.2 coming soon or do we need to downgrade? Thanks!

**Comment by drscream** [comment]
It may took a little bit longer than expected but the new version is released at GitHub and the Marketplace. If you detect any issue or problem let me know!
